# Autoprefixer will make sure your CSS works with these browsers
COMPATIBILITY:
  - "last 2 versions"
  - "ie >= 9"

# Gulp will reference these paths when it copies files
PATHS:
  # Path to dist folder
  dist: "build"
  # Paths to static assets that aren't images, CSS, or JavaScript
  assets:
    - "css/scss/**/*"
  # Paths to Sass libraries, which can then be loaded with @import
  sass:
    - "css/*/**"
